language: php

php:
  - 5.3.3
  - 5.3

env:
  - MONGO_VERSION=1.2.12 MEMCACHE_VERSION=3.0.6 APC_VERSION=3.1.13 MEMCACHED_VERSION=1.0.2
  
before_script:
  - sh bin/install_extensions.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev